package pt.pedroascenso;

/**
 * The Player class represents a player in a game of rock-paper-scissors.
 */
public class Player {

    private String name; // the name of the player
    private Generator choice; // the player's chosen move
    private int victories; // the number of victories the player has

    /**
     * Constructs a new Player object with the given name and no victories.
     *
     * @param name the name of the player
     */
    public Player(String name){
        this.name = name;
        this.victories=0;
    }

    /**
     * Returns the name of the player.
     *
     * @return the name of the player
     */
    public String getName(){
        return name;
    }

    /**
     * Sets the player's choice to a random move generated by the Generator class.
     */
    public void setChoice(){
        this.choice=Generator.randomOpt();
    }

    /**
     * Returns the player's chosen move.
     *
     * @return the player's chosen move
     */
    public Generator getChoice(){
        return choice;
    }

    /**
     * Returns the number of victories the player has.
     *
     * @return the number of victories the player has
     */
    public int getVictories() {
        return victories;
    }

    /**
     * Sets the number of victories the player has.
     *
     * @param victories the number of victories the player has
     */
    public void setVictories(int victories) {
        this.victories = victories;
    }
}
